Update thepak

diff --git a/thepak b/thepak
--- a/thepak
+++ b/thepak
@@ -22,7 +22,7 @@ unpacking () {
   if qemu-i386 $PREFIX/share/quickbms/quickbms -9 -Q etc/tools.bms "$opt" "$OUTPUT_DIR"; then
     echo "Unpacking successful!"
   else
-    echo "Unpacking failed! Please check the file and try again."
+    echo "Unpacking failed!"
   fi
 }
 
@@ -31,7 +31,7 @@ repacking () {
   if qemu-i386 $PREFIX/share/quickbms/quickbms -9 -w -r -r etc/tools.bms "$opt" "$OUTPUT_DIR"; then
     echo "Repacking successful!"
   else
-    echo "Repacking failed! Please check the file and try again."
+    echo "Repacking failed!"
   fi
 }
 
@@ -41,7 +41,7 @@ search_in_output () {
   grep -R "$search_text" "$OUTPUT_DIR"
 }
 
-# Function to handle unpacking process
+# Function to handle unpacking
 function unpack {
   prompt="Please select a file to unpack:"
   options=( $(find "$INPUT_DIR" -name "*.pak") )
@@ -60,7 +60,7 @@ function unpack {
   done
 }
 
-# Function to handle repacking process
+# Function to handle repacking
 function repack {
   prompt="Please select a file to repack:"
   options=( $(find "$INPUT_DIR" -name "*.pak") )
@@ -79,29 +79,20 @@ function repack {
   done
 }
 
-# Function to display the timer
-display_timer() {
-  local end=$((SECONDS+300))
-  while (( SECONDS < end )); do
-    tput sc
-    tput cup 0 $(($(tput cols)-10))
-    printf "Time left: %02d:%02d" $(( (end-SECONDS)/60 )) $(( (end-SECONDS)%60 ))
-    tput rc
-    sleep 1
-  done
-  echo -e "\nTime's up! Exiting..."
-  kill $$
-}
-
-# Initial login with password DRAJ
-read -p "Enter password to access Pubg-paster tool: " password
+# Password protection
+read -sp "Enter password to login: " password
+echo
 if [[ "$password" != "DRAJ" ]]; then
-  echo "Incorrect password. Exiting."
-  exit 1
+    echo "Incorrect password!"
+    exit 1
 fi
 
-# Start the timer in the background
-display_timer &
+# Timer for 5 minutes
+echo "Running tool in 5 minutes..."
+sleep 300
+
+# Set new password
+new_password="1234"
 
 # Main menu
 PS3='Please enter your choice: '
@@ -109,12 +100,6 @@ options=("Unpack" "Repack" "Search in Output" "Quit")
 select opt in "${options[@]}"; do
     case $opt in
         "Unpack")
-            # Second password before unpacking menu
-            read -p "Enter password to access unpacking menu: " password2
-            if [[ "$password2" != "1234" ]]; then
-              echo "Incorrect password. Exiting."
-              exit 1
-            fi
             unpack
             break
             ;;
